Simplify opts processing & remove unnecessary mustaches {

diff --git a/checkvolumesize b/checkvolumesize
--- a/checkvolumesize
+++ b/checkvolumesize
@@ -75,40 +75,41 @@ while true; do
   fi
 
   # For each new arg, strip the first leading `-` (if any)
-  opt="$(echo "$1" | sed 's|^-\?\([a-zA-Z0-9\?-]*\)|\1|')"
+  opt="$1"
 
-  # Handle fmt: `--buffer=10`;  Split `opt` on `=` into `opt` & `value`
-  # NOTE: prepended with `=`, because if `-d` isn't found, `cut` ignores `-f`, and returns the whole string regardless…
-  value="$(echo "=${opt}" | cut -d= -f3)"
-  if [ -n "${value}" ]; then
-    opt="$(echo "=${opt}" | cut -d= -f2)"
+  # Handle fmt: `--buffer=10`; Split `opt` on `=` into `opt` & `value`
+  #   NOTE: prepended with `=`, because if `-d` isn't found, `cut` ignores `-f`, and returns the whole string regardless…
+  value="$(echo "=$opt" | cut -d= -f3)"
+  if [ -n "$value" ]; then
+    opt="$(echo "=$opt" | cut -d= -f2)"
   fi
 
-  # Handle fmt: `--buffer 10`;  Leave `opt` as-is, and get next `value` from next arg
+  # Handle fmt: `--buffer 10`; Leave `opt` as-is, and get next `value` from next arg
   #   NOTE: only do it when next arg doesn't start with `-`
-  if [ -z "${value}" ] && [ "$2" = "${2#-}" ]; then
+  if [ -z "$value" ] && [ "$2" = "${2#-}" ]; then
     value="$2"
     shift
   fi
 
-  # Always `shift` the arg that was just used up
-  shift
+  # Remove the arg that was just used up
+  #   NOTE: `|| true` because `shift` returns non-zero on no arguments & `--help` gets no arguments
+  shift || true
 
-  case $opt in
-    h|?|-help|help)
+  case "$opt" in
+    -h|-?|--help|help)
       show_help
       exit 0
       ;;
 
-    -token)         TOKEN="${value}" ;;
-    -device)        DEVICE="${value}" ;;
-    -volume-name)   VOLUME_NAME="${value}" ;;
-    -volume-region) VOLUME_REGION="${value}" ;;
-    -buffer)        BUFFER="${value}" ;;
-    -log)           LOG=true ;;
+    --token)         TOKEN="$value" ;;
+    --device)        DEVICE="$value" ;;
+    --volume-name)   VOLUME_NAME="$value" ;;
+    --volume-region) VOLUME_REGION="$value" ;;
+    --buffer)        BUFFER="$value" ;;
+    --log)           LOG=true ;;
 
     *)
-      help_error "Unknown option: \"${opt}\""
+      help_error "Unknown option: \"$opt\""
       exit 1
       ;;
   esac
@@ -123,15 +124,15 @@ check_root () {
 
 check_dependencies () {
   for cmd in "$@"; do
-    if ! command -v "${cmd}" >/dev/null 2>&1; then
-      error "This script requires \"${cmd}\" to be installed"
+    if ! command -v "$cmd" >/dev/null 2>&1; then
+      error "This script requires \"$cmd\" to be installed"
       exit 1
     fi
   done
 }
 
 check_options () {
-  if [ -z "${TOKEN}" ] || [ -z "${DEVICE}" ] || [ -z "${VOLUME_NAME}" ] || [ -z "${VOLUME_REGION}" ]; then
+  if [ -z "$TOKEN" ] || [ -z "$DEVICE" ] || [ -z "$VOLUME_NAME" ] || [ -z "$VOLUME_REGION" ]; then
     help_error 'You are missing required options'
     exit 1
   fi
@@ -146,14 +147,14 @@ digital_ocean_api () {
   method="${method:-GET}"
 
   # If set, prepend `post_data` with `-d `
-  post_data="${post_data:+-d ${post_data}}"
+  post_data="${post_data:+-d $post_data}"
 
   curl --silent \
-    -X "${method}" \
+    -X "$method" \
     -H "Content-Type: application/json" \
-    -H "Authorization: Bearer ${TOKEN}" \
-    "${post_data}" \
-    "https://api.digitalocean.com/v2/${endpoint}"
+    -H "Authorization: Bearer $TOKEN" \
+    "$post_data" \
+    "https://api.digitalocean.com/v2/$endpoint"
 }
 
 kilobytes_to_gigabytes () {
@@ -165,14 +166,14 @@ kilobytes_to_gigabytes () {
 check_device_free_space () {
   device=$1
 
-  bytes_free=$(df --output=avail "${device}" | tail -n 1)
-  kilobytes_to_gigabytes "${bytes_free}"
+  bytes_free=$(df --output=avail "$device" | tail -n 1)
+  kilobytes_to_gigabytes "$bytes_free"
 }
 
 mountpoint_to_device () {
   mountpoint=$1
 
-  df --output=source "${mountpoint}" | tail -n 1
+  df --output=source "$mountpoint" | tail -n 1
 }
 
 main () {
@@ -181,7 +182,7 @@ main () {
   check_options
 
   # Check available volume space
-  log "Checking available space on device \"${DEVICE}\" is above ${BUFFER}GB requirement..."
+  log "Checking available space on device \"$DEVICE\" is above ${BUFFER}GB requirement..."
   volume_free_space=$(check_device_free_space "$DEVICE")
   if [ "$volume_free_space" -gt "$BUFFER" ]; then
     log "${volume_free_space}GB available, all good!"
@@ -193,24 +194,24 @@ main () {
   start_time="$(date +%s)"
 
   # Get volume data
-  log "Getting data for volume \"${VOLUME_NAME}\" in region \"${VOLUME_REGION}\"..."
-  volume_json=$(digital_ocean_api "volumes?region=${VOLUME_REGION}" | jq -r ".volumes[] | select(.name==\"${VOLUME_NAME}\")")
+  log "Getting data for volume \"$VOLUME_NAME\" in region \"$VOLUME_REGION\"..."
+  volume_json=$(digital_ocean_api "volumes?region=$VOLUME_REGION" | jq -r ".volumes[] | select(.name==\"$VOLUME_NAME\")")
   volume_id=$(echo "$volume_json" | jq -r .id)
   volume_size=$(echo "$volume_json" | jq -r .size_gigabytes)
-  log "Volume ID is \"${volume_id}\" and is currently ${volume_size}GB"
+  log "Volume ID is \"$volume_id\" and is currently ${volume_size}GB"
 
   # Increase volume size
   new_volume_size=$(( volume_size + BUFFER ))
   log "Increasing volume size to ${new_volume_size}GB..."
-  action_json=$(digital_ocean_api "volumes/${volume_id}/actions" '{"type":"resize","size_gigabytes":'${new_volume_size}'}')
-  action_id="$(echo "${action_json}" | jq -r '.action.id')"
-  log "Created action \"${action_id}\""
+  action_json=$(digital_ocean_api "volumes/$volume_id/actions" '{"type":"resize","size_gigabytes":'$new_volume_size'}')
+  action_id="$(echo "$action_json" | jq -r '.action.id')"
+  log "Created action \"$action_id\""
 
   # Wait for volume resize
   log "Waiting for action to complete..."
   while true; do
-    resize_status=$(digital_ocean_api "actions/${action_id}" | jq -r '.action.status')
-    if [ "${resize_status}" = "completed" ]; then
+    resize_status=$(digital_ocean_api "actions/$action_id" | jq -r '.action.status')
+    if [ "$resize_status" = "completed" ]; then
       break
     fi
 
@@ -221,21 +222,21 @@ main () {
 
   # Resize filesystem
   log "Resizing filesystem..."
-  sudo resize2fs "$(mountpoint_to_device "${DEVICE}")" 2>&1 | while read -r line; do
-    if [ "${line}" != "" ]; then
+  sudo resize2fs "$(mountpoint_to_device "$DEVICE")" 2>&1 | while read -r line; do
+    if [ "$line" != "" ]; then
       log "$line"
     fi
   done
   log "Filesystem resize complete!"
 
   # Show new available space on completion
-  new_free_space=$(check_device_free_space "${DEVICE}")
-  log "Device \"${DEVICE}\" now has ${new_free_space}GB available"
+  new_free_space=$(check_device_free_space "$DEVICE")
+  log "Device \"$DEVICE\" now has ${new_free_space}GB available"
 
   # Show duration
   now="$(date +%s)"
   duration=$(( now - start_time ))
-  log "Completed in ${duration} seconds"
+  log "Completed in $duration seconds"
 }
 
 main
